version: "3.8"
services:
  aigpro_benchmark:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    volumes:
      - .:/app  # Mount current directory to /app in container
    # Ports are kept just in case, though not strictly needed for batch training
    ports:
      - "8097:8097"
    container_name: aigpro_benchmark
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    ipc: host
    tty: true
    environment:
      - PYTHONPATH=/app:/app/aigpro:${PYTHONPATH}